<footer>
<section id="footer-area">
	<section id="footer-outer-block">
			<aside class="footer-segment first">
					<h4>&nbsp;</h4>
						<ul>
							<li><a href="#">one linkylink</a></li>
							<li><a href="#">two linkylinks</a></li>
							<li><a href="#">three linkylinks</a></li>
							</ul>
			</aside><!-- end of #first footer segment -->

			<aside class="footer-segment second">
					<h4>&nbsp;</h4>
						<ul>
							<li><a href="#">one linkylink</a></li>
							<li><a href="#">two linkylinks</a></li>
							<li><a href="#">three linkylinks</a></li>
						</ul>
			</aside><!-- end of #second footer segment -->

			<aside class="footer-segment third">
					<h4>&nbsp;</h4>
						<ul>
							<li><a href="#">one linkylink</a></li>
							<li><a href="#">two linkylinks</a></li>
							<li><a href="#">three linkylinks</a></li>
						</ul>
			</aside><!-- end of #third footer segment -->
					
			<aside class="footer-segment last">
					<h4>&nbsp;</h4>
						<p>&copy; 2012 <a href="#">www.test.com</a></p>
			</aside><!-- end of #fourth footer segment -->

	</section><!-- end of footer-outer-block -->

</section><!-- end of footer-area -->
</footer>
	
</div><!-- #wrapper -->
<script src="../js/connexion.js"></script>
<script type='text/javascript' src='js/example.js'></script>
</body>
</html>
